Patch to make 0.13 usable
Should fix the
```
ERROR: LoadError: ArgumentError: Package Tables does not have TableTraits in its dependencies:
- If you have Tables checked out for development and have
  added TableTraits as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Tables
```